version: '3.7'
services:
  web:
    build:
      context: .
#      args:
#        - http_proxy=http://proxy.local.jp:8080
#        - https_proxy=http://proxy.local.jp:8080
#        - HTTP_PROXY=http://proxy.local.jp:8080
#        - HTTPS_PROXY=http://proxy.local.jp:8080
    ports:
      - '4000:4000'
    command: iex -S mix phx.server
    environment:
      - MIX_ENV=dev
      - PORT=4000
#      - http_proxy=http://proxy.local.jp:8080
#      - https_proxy=http://proxy.local.jp:8080
#      - HTTP_PROXY=http://proxy.local.jp:8080
#      - HTTPS_PROXY=http://proxy.local.jp:8080
    volumes:
      - ./proj:/proj

  db:
    image: postgres:10.10
    container_name: postgres_host
    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
      - IMPORT_FROM_DIR=/data
    ports:
      - 5432:5432
    volumes:
      - ./db/sh:/docker-entrypoint-initdb.d
      - ./db/data:/data
      - ./db/storage:/var/lib/postgresql/data
